### PR TITLE
feat: expose useContextMap

### PR DESCRIPTION
**Pull request by hansottowirtz**
Exposes `useAllContexts`.

This would be useful for me in [@bubblydoo/angular-react](https://github.com/bubblydoo/angular-react#reading-react-contexts-in-angular), as I can use this function to inject React contexts into Angular.

See [the usage of useAllContexts](https://github.com/bubblydoo/angular-react/blob/main/projects/angular-react/src/lib/passed-react-context-token/use-create-passed-react-context.ts) (I've temporarily forked its-fine) and [an example of an Angular component using it](https://github.com/bubblydoo/angular-react/blob/main/stories/injected-contexts.stories.tsx) and [the deployed example](http://localhost:6006/?path=/story/basics-injected-contexts--showcase).

### CODE REVIEW

**Comment by CodyJasonBennett** [comment]
I'm debating between this and having `useContextBridge` accept a `context` map to write into. Not sure how confusing in/out arguments are though.

**Comment by hansottowirtz** [comment]
Maybe we can also expose a `useContextBridgeFromContexts` that accepts the map?

And then
```ts
export function useContextBridge() {
  const contexts = useAllContexts()
  return useContextBridgeFromContexts(contexts)
}
```

Might make the api feel bloated though.

**Comment by CodyJasonBennett** [comment]
I think I'm happy with this PR and exposing the traversal mechanism, but maybe name it `useContextMap` and export `type ContextMap<T = any> = Map<React.Context<T>, T>` as its return type.

**Comment by hansottowirtz** [comment]
I'm not sure if that is the correct type, as that would imply all the possible contexts on the context map are of type `T`.

Unfortunately the `.get` method of a Map is not generic itself, because this function would make sense:

```ts
function get<K>(key: React.Context<K>): K {
  return map.get(key)
}
```

We could rewrite the `get` and `keys` functions in this way and expose those instead of the map to make it more type-safe, but that would probably overcomplicate it. I suggest we just keep `ContextMap = Map<React.Context<any>, any>`.

**Comment by hansottowirtz** [comment]
Just had an idea, this also works and is not too complicated.

```ts
type ContextMap = Map<React.Context<any>, any> & {
  get<T>(context: React.Context<T>): T | undefined
}
```

**Comment by CodyJasonBennett** [comment]
I see. I'm fine with whatever, just that it be exported as a type.

**Comment by hansottowirtz** [comment]
Alright, then I think it can be merged.

**Pull request merged**
